lifeot:
  name: lifeot yml
spring:
  profiles:
    active: dev

---
spring:
  profiles: default
lifeot:
  name: lifeot default
  sessionTimeout: 30
  readTimeout: 1000
  number: 10
  myPojo:
    - name: my name
      description: my description
    - name: another name
      description: another description

---
spring:
  profiles: prod
lifeot:
  name: lifeot prod
  myPojo:
    - name: my name
      description: my description
    - name: another name
      description: another description
    - name: another name
      description: another description

---
spring:
  profiles: dev
  output:
    ansi:
      enabled: always
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
      html-application-cache: true
  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: true
    pathmatch:
      use-suffix-pattern: true
#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/html
lifeot:
  name: lifeot dev
  myPojo:
    - name: my name
      description: my description
logging:
  file: ./logs/my.log
#  level:
#    root: WARN
#    org:
#      springframework:
#        web: DEBUG
